### ISSUE TITLE
meta: Export tags from music file to `Meta` instance

### ISSUE THREAD

**Issue by Gateswong** [Gateswong/GatesMusicPet#2]
For flac files, the tags can be export by `metaflac --export-tags=TAGFILE FILENAME`. 

Now it's necessary to parse the tags and save them into `Meta` instance.
- [ ] Update README file
- [ ] Need to be able to use the ipython notebook to go through the whole converting processes.
  - [x] Convert whole track + CUE files
  - [ ] Convert seperate tracks with or without CUE files.
- [ ] Loads one or more `flac` files, then make an instance of `AlbumList`.

**Comment by MikeLing** [comment]
Hmm, I would like to fix that issue. But I will start my work after know more about TRACK and CUE.

**Comment by Gateswong** [comment]
You can implement this in branch issue_3's first merge.

**Comment by Gateswong** [comment]
Resolved by pull #9
