### ISSUE TITLE
Write tests for `meta.py`, `utils.py` and `audio/*.py`

### ISSUE THREAD

**Issue by Gateswong** [Gateswong/GatesMusicPet#6]
Need to write unit tests for these files. To start working with this issue, create branch from `issue_3` if it is not merged into master.
- `meta.py`
  - [ ] Unit tests for class `Meta`
  - [ ] Unit tests for class `Track`
  - [ ] Unit tests for class `Album`
  - [ ] Unit tests for class `AlbumList`
  - [ ] Unit tests for function `parse_cue()`
  - [ ] Unit tests for function `parse_ini()`
- `utils.py`
  - [x] Unit tests for function `trim_quote()`
  - [x] Unit tests for function `to_unicode()`
  - [x] Unit tests for function `remove_bom()`
  - [x] Unit tests for function `iconv_file()`
  - [x] Unit tests for function `filename_safe()`
  - [x] Unit tests for function `cli_escape()`
- `audio/base.py`
  - [ ] Unit tests for class `AudioFile`
  - [ ] Unit tests for class `PictureMixin`
- `audio/flac.py`
  - [ ] Unit tests for class `FLAC`
